### ISSUE TITLE
Can't getUrl from a private s3 bucket

### ISSUE THREAD

**Issue by SergioVago** [adonisjs/drive-s3#15]
https://github.com/adonisjs/bodyparser/blob/6e7cf68edba9ddae39cc7d7be1ab7665e18919d9/src/Multipart/File.ts#L253

**Comment by Julien-R44** [comment]
Can you please make a little effort and give more information about the problem you are facing?

**Comment by SergioVago** [comment]
Sure. 

A have this code for upload some file on S3 Bucket
```js
const { account_id: accountId } = request.only(['account_id'])
const file = request.file('file')

if (!file) {
    return
}

const name = uuid() + '-' + file.clientName

const createdFile = await AccountFile.create({
    name,
    accountId,
})

await file.moveToDisk(
    'accounts-files',
    {
        name,
    },
    Env.get('DRIVE_DISK')
)
```

I checked my bucket and i have the file uploaded, but have this error on my catch
```js
 err: {
      "type": "TypeError",
      "message": "this.adapter.config.endpoint is not a function",
      "stack":
          TypeError: this.adapter.config.endpoint is not a function
              at S3Driver.getUrl (D:\Github\app-v1\server\node_modules\@adonisjs\drive-s3\build\src\Drivers\S3.js:220:66)
              at File.moveToDisk (D:\Github\app-v1\server\node_modules\@adonisjs\bodyparser\build\src\Multipart\File.js:177:44)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
              at AccountFilesController.store (D:\Github\app-v1\server\app\Controllers\Http\AccountFilesController.ts:25:5)
              at Object.PreCompiler.runRouteHandler [as fn] (D:\Github\app-v1\server\node_modules\@adonisjs\http-server\build\src\Server\PreCompiler\index.js:47:31)
              at UserTypeLimiter.handle (D:\Github\app-v1\server\app\Middleware\UserTypeLimiter.ts:55:5)
              at AuthMiddleware.handle (D:\Github\app-v1\server\app\Middleware\Auth.ts:87:5)
              at Server.handleRequest (D:\Github\app-v1\server\node_modules\@adonisjs\http-server\build\src\Server\index.js:108:13)
      "status": 500
    }
```

My bucket is a private bucket, so I suspect that method getUrl is the problem, because we need to use getSignedUrl in this case

Locally this code is working with a DRIVE_DISK=local

**Comment by thetutlage** [comment]
Our friends at AWS are on a streak on releasing breaking changes. So let's wait for this to be addressed https://github.com/aws/aws-sdk-js-v3/issues/4122

**Comment by SergioVago** [comment]
Nice! Thanks for the support :)

**Comment by zeornelas** [comment]
I'm having the same problem. I did a fresh install of an existing problem and I'm now stuck with this issue.

Does anyone have any news about this?

Can't we **temporarily** force the `aws-sdk` version we are using, until this gets fixed, on `@adonis/drive-s3`?
I had a look into @thetutlage comments at https://github.com/aws/aws-sdk-js-v3/issues/4122, and it seems `aws-sdk@3.190.0` doesn't show signs of this problem.

**Comment by zeornelas** [comment]
@thetutlage https://github.com/aws/aws-sdk-js-v3/issues/4122 has been closed. Can this now get fixed on drive-s3?

**Comment by zeornelas** [comment]
While this doesn't get fixed you can override the `aws-sdk` version on your local package.json by adding the following:
```
"overrides": {
    "@adonisjs/drive-s3": {
      "@aws-sdk/client-s3": "3.190.0",
      "@aws-sdk/lib-storage": "3.190.0"
    }
  }
```

**Comment by mkevison** [comment]
> Embora isso não seja corrigido, você pode substituir a `aws-sdk`versão em seu package.json local adicionando o seguinte:
> 
> ```
> "overrides": {
>     "@adonisjs/drive-s3": {
>       "@aws-sdk/client-s3": "3.190.0",
>       "@aws-sdk/lib-storage": "3.190.0"
>     }
>   }
> ```

Thanks! this worked for me.

**Comment by wellkamp** [comment]
> While this doesn't get fixed you can override the `aws-sdk` version on your local package.json by adding the following:
> 
> ```
> "overrides": {
>     "@adonisjs/drive-s3": {
>       "@aws-sdk/client-s3": "3.190.0",
>       "@aws-sdk/lib-storage": "3.190.0"
>     }
>   }
> ```


Hi! This didn't work for me any other solution?

**Comment by cledsonmedeiros** [comment]
So sad, this is still not working...

**Comment by MANTENN** [comment]
Im in the same boat, the part onFile runs but the `putStream` prevents the function from returning and keeps on infinitely running without returning an error

**Comment by albersanmar** [comment]
I think this error is due to the fact that the @aws-sdk/client-s3 package made an important change and now you have to specify the S3 endpoint

A solution would be to install a version prior to 3.192
In my case I specified the endpoint in the Driver configuration

![image](https://user-images.githubusercontent.com/45761567/233473244-55b21764-4cf3-4f5e-af7b-003a37137fa6.png)

**Comment by MANTENN** [comment]
> I think this error is due to the fact that the @aws-sdk/client-s3 package made an important change and now you have to specify the S3 endpoint
> 
> A solution would be to install a version prior to 3.192 In my case I specified the endpoint in the Driver configuration
> 
> ![image](https://user-images.githubusercontent.com/45761567/233473244-55b21764-4cf3-4f5e-af7b-003a37137fa6.png)

I tried that, didn't help. I ended up using S3 SDK instead of tinkering with the Drive package
