### ISSUE TITLE
 "s3" driver is not supported by "DriveManager"

### ISSUE THREAD

**Issue by chadhobson** [adonisjs/drive-s3#18]
## Package version
Latest

## Node.js and npm version
Latest

## Sample Code (to reproduce the issue)
Anything from docs

Is this working for anyone right now on the latest versions of everything? I'm just getting this error message:

 "s3" driver is not supported by "DriveManager"

I don't have S3_ENDPOINT set because thats not terminology native to AWS/S3 so I don't have a clue what it expects there and the docs don't show an example.

What am I missing?

**Comment by chadhobson** [comment]
Grrrr... still getting used to v5. This one is on me folks. I'll take the L though and leave this issue here for some other future moron. :-)

If you get this error, run this command to resolve it...

node ace configure @adonisjs/drive-s3

**Comment by chadhobson** [comment]
One more note because this 100% should be in the docs...

S3_ENDPOINT=https://s3.amazonaws.com

That's not anything anyone using AWS would expect to see but there you go. All is working fine for me now with that addition to the .env file.

**Comment by cledsonmedeiros** [comment]
> One more note because this 100% should be in the docs...
> 
> S3_ENDPOINT=https://s3.amazonaws.com
> 
> That's not anything anyone using AWS would expect to see but there you go. All is working fine for me now with that addition to the .env file.

Thank you so much!
