### ISSUE TITLE
NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

### ISSUE THREAD

**Issue by albersanmar** [adonisjs/drive-s3#19]
I am using this package and in the developer console I get this message, "NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023." It seems Amazon is suggesting to switch to version 3 of the @aws-sdk/client-s3 package.

I mention this, because in the future there may start to be bugs.

**Comment by JonhnyDev** [comment]
up

**Comment by thetutlage** [comment]
We are using the latest version of AWS SDK and it shouldn't be a problem. Used versions are

```json
{
  "@aws-sdk/client-s3": "^3.405.0",
  "@aws-sdk/lib-storage": "^3.405.0",
}
```
