### ISSUE TITLE
[Bug] s3 endpoint issue

### ISSUE THREAD

**Issue by Danhhoa** [adonisjs/drive-s3#20]
## Bug Report

I'm facing with issue when upload to s3 bucket with moveToDisk() method via Drive if I don't have Endpoint
I see endpoint is optional props, but it required here?

![image](https://github.com/adonisjs/drive-s3/assets/134903763/fc5c3919-6d95-4e03-a5c7-08f5d4ff2dfc)

## Behavior
Videos still upload success into S3 bucket but it throw errors

## Package version

"@adonisjs/drive-s3": "^1.3.2",

## Node.js and npm version

Node 18.16.0

## Sample Code

Drive config (Because I don't have endpoint)
![image](https://github.com/adonisjs/drive-s3/assets/73631119/8bf890f7-58ba-404f-9a9d-7a668c3b9c64)

![image](https://github.com/adonisjs/drive-s3/assets/134903763/8b5622a6-2354-4673-b85e-a90fa0d8e6f8)

![image](https://github.com/adonisjs/drive-s3/assets/134903763/bda42eb2-c2b4-4eb8-b9f6-556f8d215af5)

**Comment by casperboone** [comment]
See #15

I used
```
  "resolutions": {
    "@aws-sdk/client-s3": "3.190.0",
    "@aws-sdk/lib-storage": "3.190.0"
  }
  ```
in my package.json to make it work.
