### ISSUE TITLE
Get URL Problem

### ISSUE THREAD

**Issue by tianjos** [adonisjs/drive-s3#23]
## Prerequisites
drive.getUrl doesn't returns the slash between bucket name and location

## Package version
1.3.3

## Node.js and npm version
node 18, npm 8

## Sample Code (to reproduce the issue)
Drive.use('s3').bucket(bucketName).getUrl(location) -> http://localhost:9000/images/foo.png # expected behavior
Drive.use('s3').bucket(bucketName).getUrl(location) -> http://localhost:9000/imagesfoo.png # actual behavior

**Comment by tianjos** [comment]
PR #17 has a breaking change on getUrl

from this
`    return `${href}/${this.config.bucket}/${location}``

to this
    `return `${this.cachedBucketUrl}${location}``

**Comment by thetutlage** [comment]
Hello, we have a test here that confirms the URL returned by `getUrl` is correct. https://github.com/adonisjs/drive-s3/blob/develop/test/s3-driver.spec.ts#L1156-L1158

Can you please create a breaking test and I will look into it

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
